# Generated by Django 3.1 on 2022-12-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallary',
            new_name='ProductGallery',
        ),
    ]
